pipeline:
  lint-charts:
    image: guangbo/chart-testing:v2.0.2-rancher1
    commands:
      - git remote add rancher-charts https://shengzhihao1996/rancher/charts
      - git fetch rancher-charts master
      - ct lint --config test/ct.yaml
